name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger from the Actions UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: production  # Optional: add environments/protection

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
      TF_VAR_tfe_token: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate terraform.tfvars from template, env, and input.json
        run: python templatize.py
        env:
          # Use workflow input, fallback to secrets/defaults if missing
          ORGANIZATION_CODE: ${{ github.event.inputs.organization_code }}
          LOB_CODE: ${{ github.event.inputs.lob_code }}
          APP_CODE: ${{ github.event.inputs.app_code }}
          APP_NAME: ${{ github.event.inputs.application_name }}
          APP_PLATFORM: ${{ github.event.inputs.application_platform }}
          APP_ENVT: ${{ github.event.inputs.environments }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
          TF_VAR_tfe_token: ${{ secrets.TF_API_TOKEN }}
